### ISSUE TITLE
Error when running pep_patch_hydrophobic  TypeError: compute_sas() got an unexpected keyword argument 'return_buffer'

### ISSUE THREAD

**Issue by adam-kral** [liedllab/surface_analyses#28]
Hi, when running pep_patch_hydrophobic (without msms) I now get this error:

Traceback (most recent call last):
   File "pep_patch/condaenv/lib/python3.11/site-packages/surface_analyses/hydrophobic_potential.py", line 37, in hydrophobic_potential
    ses = compute_ses(grid, frame, radii, solv_rad)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pep_patch/condaenv/lib/python3.11/site-packages/surface_analyses/surface.py", line 318, in compute_ses
    return compute_ses_gisttools(grid, xyz, radii, solvent_radius=solvent_radius)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pep_patch/condaenv/lib/python3.11/site-packages/surface_analyses/surface.py", line 340, in compute_ses_gisttools
    solv_dist = ses_grid(grid, xyz, radii, solvent_radius=solvent_radius)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pep_patch/condaenv/lib/python3.11/site-packages/surface_analyses/surface.py", line 328, in ses_grid
    sas, distbuffer = compute_sas(grid, xyz, radii=radii, solvent_radius=solvent_radius, return_buffer=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: compute_sas() got an unexpected keyword argument 'return_buffer'

I could also use msms (I see added recently), but I am not sure it is compiled for arm mac.

**Comment by fwaibl** [comment]
Hi. Thanks for your bug report. Indeed, this seems to have creeped in when we added the msms support. I'll try to upload a fix today.
