### ISSUE TITLE
pep_patch_hydrophobic: KeyError: ('HIS', 'N')

### ISSUE THREAD

**Issue by Epannec** [liedllab/surface_analyses#31]
Hi, 

I'm trying to run pep_patch_hydrophobic on a pdb file (Fc-fragment) with the following command:
`pep_patch_hydrophobic FC.pdb FC.pdb --scale eisenberg --potential --patches`
It always prematurely stops with the following error:
```
[...]
PdbAtom(232, 30, VAL, CB, 6, atom_type=None)
PdbAtom(233, 30, VAL, CG1, 6, atom_type=None)
PdbAtom(234, 30, VAL, CG2, 6, atom_type=None)
PdbAtom(235, 31, SER, N, 7, atom_type=None)
PdbAtom(236, 31, SER, CA, 6, atom_type=None)
PdbAtom(237, 31, SER, C, 6, atom_type=None)
PdbAtom(238, 31, SER, O, 8, atom_type=None)
PdbAtom(239, 31, SER, CB, 6, atom_type=None)
PdbAtom(240, 32, HIS, N, 7, atom_type=None)
Traceback (most recent call last):
  File "*edit*/PEP-Patch/PEP-Patch_venv/bin/pep_patch_hydrophobic", line 8, in <module>
    sys.exit(main())
  File "*edit*/PEP-Patch/PEP-Patch_venv/lib/python3.10/site-packages/surface_analyses/commandline_hydrophobic.py", line 33, in main
    run_hydrophobic(parm, traj, **vars(args))
  File "*edit*/PEP-Patch/PEP-Patch_venv/lib/python3.10/site-packages/surface_analyses/commandline_hydrophobic.py", line 173, in run_hydrophobic
    propensities = np.asarray(grouper([propensity_map(a) for a in atoms]))
  File "*edit*/PEP-Patch/PEP-Patch_venv/lib/python3.10/site-packages/surface_analyses/commandline_hydrophobic.py", line 173, in <listcomp>
    propensities = np.asarray(grouper([propensity_map(a) for a in atoms]))
  File "*edit*/PEP-Patch/PEP-Patch_venv/lib/python3.10/site-packages/surface_analyses/propensities.py", line 14, in propensity
    return amber_to_eisen_value(a)
  File "*edit*/PEP-Patch/PEP-Patch_venv/lib/python3.10/site-packages/surface_analyses/eisenberg.py", line 59, in amber_to_eisen_value
    return EISENBERG_PARAMS[amber_to_eisen_type(atom)]
  File "*edit*/PEP-Patch/PEP-Patch_venv/lib/python3.10/site-packages/surface_analyses/eisenberg.py", line 56, in amber_to_eisen_type
    return eisen_type(atom.atom_type, atom.name, atom.residue_label)
  File "*edit*/PEP-Patch/PEP-Patch_venv/lib/python3.10/site-packages/surface_analyses/pdb.py", line 168, in atom_type
    return ATOM_DATA[key][0]
KeyError: ('HIS', 'N')
```

I'm not quite sure what is going on here, any advice would be welcome!

Thank you in advance,
Erwin

**Comment by vhoer** [comment]
Hi Erwin,
this error arises due to the naming of the HIS residue. Internally, we use AMBER atom types where HIS is either classified as HIE (proton at epsilon position), HID (delta position) or HIP (both protonated). 
For a simple fix you could rename all your HIS residues accordingly. 

@fwaibl: In the future we might want to assume every HIS to be HIE  (or throw a warning to the user).  What are your thoughts on this?
Best regards, 
Valentin

**Comment by fwaibl** [comment]
Hi Erwin and Valentin,

Thanks for reporting this! Just a few comments from my side:
* just to be sure, I wanted to clarify that this is the atomic Eisenberg scale taken from https://www.nature.com/articles/319199a0, in contrast to the more commonly used residue-based Eisenberg scale published in https://doi.org/10.1039/FS9821700109
* from our side, the code for the atomic Eisenberg scale could be simplified, because it only uses the atomic element, but we currently define it for every residue + atom name combination. I originally did it like this to be consistent with the Crippen scale, which is more difficult to assign because it needs bond information. But we should definitely simplify it sooner or later.
* Since we load a PDB file including hydrogen atoms, we could assign the histidine state (delta, epsilon, or protonated) based on which hydrogen atoms are there. That would allow us to treat HIS residues correctly with all protonation states.
